/**
* \brief Look-up tables for 3D-SWIG trajectories
* 
* This code was auto-generated by the MATLAB function generateHeaderCode.m
* Calculation of dMPhi1 and dMPhi2 must be handled by the sequence code, e.g.:
* 
*     > const double phi1 = 0.465571231876768
*     > const double phi2 = 0.682327803828019
*     > double u_dMPhi1 = fmod(lReorderIndex*phi1, 1.0);
*     > double u_dMPhi2 = fmod(lReorderIndex*phi2, 1.0);
* 
* If this code is useful for your research, please consider citing:
* Fyrdahl, A, Ullvin, A, Ramos, JG, Seiberlich, N, Ugander, M, Sigfridsson, A. Three-dimensional sector-wise golden angle–improved k-space uniformity after electrocardiogram binning. Magn Reson Med. 2023; 90( 3): 1041- 1052. doi: 10.1002/mrm.29698
* 
* 2023 – Alexander Fyrdahl, PhD (alexander.fyrdahl@ki.se)
*/

void fSWIGTraj48(long u_lTrig, double dMPhi1, double dMPhi2, double* x, double* y, double *z)
{
    switch(u_lTrig%48) {
    case(0):
        *x = (-dMPhi1)/2;
        *y = (dMPhi2-1)/2;
        *z = 1;
        break;
    case(1):
        *x = (-dMPhi1+1)/2;
        *y = (dMPhi2-1)/2;
        *z = 1;
        break;
    case(2):
        *x = (-dMPhi1+1)/2;
        *y = (dMPhi2)/2;
        *z = 1;
        break;
    case(3):
        *x = (-dMPhi1)/2;
        *y = (dMPhi2)/2;
        *z = 1;
        break;
    case(4):
        *x = (-dMPhi1-1)/2;
        *y = (dMPhi2)/2;
        *z = 1;
        break;
    case(5):
        *x = (-dMPhi1-1)/2;
        *y = (dMPhi2-1)/2;
        *z = 1;
        break;
    case(6):
        *x = (-dMPhi1-1)/2;
        *y = (dMPhi2-2)/2;
        *z = 1;
        break;
    case(7):
        *x = (-dMPhi1)/2;
        *y = (dMPhi2-2)/2;
        *z = 1;
        break;
    case(8):
        *x = (-dMPhi1+1)/2;
        *y = (dMPhi2-2)/2;
        *z = 1;
        break;
    case(9):
        *x = (-dMPhi1+2)/2;
        *y = (dMPhi2-2)/2;
        *z = 1;
        break;
    case(10):
        *x = (-dMPhi1+2)/2;
        *y = (dMPhi2-1)/2;
        *z = 1;
        break;
    case(11):
        *x = (-dMPhi1+2)/2;
        *y = (dMPhi2)/2;
        *z = 1;
        break;
    case(12):
        *x = (-dMPhi1+2)/2;
        *y = (dMPhi2+1)/2;
        *z = 1;
        break;
    case(13):
        *x = (-dMPhi1+1)/2;
        *y = (dMPhi2+1)/2;
        *z = 1;
        break;
    case(14):
        *x = (-dMPhi1)/2;
        *y = (dMPhi2+1)/2;
        *z = 1;
        break;
    case(15):
        *x = (-dMPhi1-1)/2;
        *y = (dMPhi2+1)/2;
        *z = 1;
        break;
    case(16):
        *x = -1;
        *y = (dMPhi1+1)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(17):
        *x = -1;
        *y = (dMPhi1)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(18):
        *x = -1;
        *y = (dMPhi1-1)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(19):
        *x = -1;
        *y = (dMPhi1-2)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(20):
        *x = (-dMPhi1-1)/2;
        *y = -1;
        *z = (dMPhi2+1)/2;
        break;
    case(21):
        *x = (-dMPhi1)/2;
        *y = -1;
        *z = (dMPhi2+1)/2;
        break;
    case(22):
        *x = (-dMPhi1+1)/2;
        *y = -1;
        *z = (dMPhi2+1)/2;
        break;
    case(23):
        *x = (-dMPhi1+2)/2;
        *y = -1;
        *z = (dMPhi2+1)/2;
        break;
    case(24):
        *x = 1;
        *y = (dMPhi1-2)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(25):
        *x = 1;
        *y = (dMPhi1-1)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(26):
        *x = 1;
        *y = (dMPhi1)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(27):
        *x = 1;
        *y = (dMPhi1+1)/2;
        *z = (dMPhi2+1)/2;
        break;
    case(28):
        *x = (-dMPhi1+2)/2;
        *y = 1;
        *z = (dMPhi2+1)/2;
        break;
    case(29):
        *x = (-dMPhi1+1)/2;
        *y = 1;
        *z = (dMPhi2+1)/2;
        break;
    case(30):
        *x = (-dMPhi1)/2;
        *y = 1;
        *z = (dMPhi2+1)/2;
        break;
    case(31):
        *x = (-dMPhi1-1)/2;
        *y = 1;
        *z = (dMPhi2+1)/2;
        break;
    case(32):
        *x = -1;
        *y = (dMPhi1+1)/2;
        *z = (dMPhi2)/2;
        break;
    case(33):
        *x = -1;
        *y = (dMPhi1)/2;
        *z = (dMPhi2)/2;
        break;
    case(34):
        *x = -1;
        *y = (dMPhi1-1)/2;
        *z = (dMPhi2)/2;
        break;
    case(35):
        *x = -1;
        *y = (dMPhi1-2)/2;
        *z = (dMPhi2)/2;
        break;
    case(36):
        *x = (-dMPhi1-1)/2;
        *y = -1;
        *z = (dMPhi2)/2;
        break;
    case(37):
        *x = (-dMPhi1)/2;
        *y = -1;
        *z = (dMPhi2)/2;
        break;
    case(38):
        *x = (-dMPhi1+1)/2;
        *y = -1;
        *z = (dMPhi2)/2;
        break;
    case(39):
        *x = (-dMPhi1+2)/2;
        *y = -1;
        *z = (dMPhi2)/2;
        break;
    case(40):
        *x = 1;
        *y = (dMPhi1-2)/2;
        *z = (dMPhi2)/2;
        break;
    case(41):
        *x = 1;
        *y = (dMPhi1-1)/2;
        *z = (dMPhi2)/2;
        break;
    case(42):
        *x = 1;
        *y = (dMPhi1)/2;
        *z = (dMPhi2)/2;
        break;
    case(43):
        *x = 1;
        *y = (dMPhi1+1)/2;
        *z = (dMPhi2)/2;
        break;
    case(44):
        *x = (-dMPhi1+2)/2;
        *y = 1;
        *z = (dMPhi2)/2;
        break;
    case(45):
        *x = (-dMPhi1+1)/2;
        *y = 1;
        *z = (dMPhi2)/2;
        break;
    case(46):
        *x = (-dMPhi1)/2;
        *y = 1;
        *z = (dMPhi2)/2;
        break;
    case(47):
        *x = (-dMPhi1-1)/2;
        *y = 1;
        *z = (dMPhi2)/2;
        break;
    default:
        *x = 0.0;
        *y = 0.0;
        *z = 0.0;
        break;
    }
}

void fSWIGTraj108(long u_lTrig, double dMPhi1, double dMPhi2, double* x, double* y, double *z)
{
    switch(u_lTrig%108) {
    case(0):
        *x = (-dMPhi1)/3;
        *y = (dMPhi2-1)/3;
        *z = 1;
        break;
    case(1):
        *x = (-dMPhi1+1)/3;
        *y = (dMPhi2-1)/3;
        *z = 1;
        break;
    case(2):
        *x = (-dMPhi1+1)/3;
        *y = (dMPhi2)/3;
        *z = 1;
        break;
    case(3):
        *x = (-dMPhi1)/3;
        *y = (dMPhi2)/3;
        *z = 1;
        break;
    case(4):
        *x = (-dMPhi1-1)/3;
        *y = (dMPhi2)/3;
        *z = 1;
        break;
    case(5):
        *x = (-dMPhi1-1)/3;
        *y = (dMPhi2-1)/3;
        *z = 1;
        break;
    case(6):
        *x = (-dMPhi1-1)/3;
        *y = (dMPhi2-2)/3;
        *z = 1;
        break;
    case(7):
        *x = (-dMPhi1)/3;
        *y = (dMPhi2-2)/3;
        *z = 1;
        break;
    case(8):
        *x = (-dMPhi1+1)/3;
        *y = (dMPhi2-2)/3;
        *z = 1;
        break;
    case(9):
        *x = (-dMPhi1+2)/3;
        *y = (dMPhi2-2)/3;
        *z = 1;
        break;
    case(10):
        *x = (-dMPhi1+2)/3;
        *y = (dMPhi2-1)/3;
        *z = 1;
        break;
    case(11):
        *x = (-dMPhi1+2)/3;
        *y = (dMPhi2)/3;
        *z = 1;
        break;
    case(12):
        *x = (-dMPhi1+2)/3;
        *y = (dMPhi2+1)/3;
        *z = 1;
        break;
    case(13):
        *x = (-dMPhi1+1)/3;
        *y = (dMPhi2+1)/3;
        *z = 1;
        break;
    case(14):
        *x = (-dMPhi1)/3;
        *y = (dMPhi2+1)/3;
        *z = 1;
        break;
    case(15):
        *x = (-dMPhi1-1)/3;
        *y = (dMPhi2+1)/3;
        *z = 1;
        break;
    case(16):
        *x = (-dMPhi1-2)/3;
        *y = (dMPhi2+1)/3;
        *z = 1;
        break;
    case(17):
        *x = (-dMPhi1-2)/3;
        *y = (dMPhi2)/3;
        *z = 1;
        break;
    case(18):
        *x = (-dMPhi1-2)/3;
        *y = (dMPhi2-1)/3;
        *z = 1;
        break;
    case(19):
        *x = (-dMPhi1-2)/3;
        *y = (dMPhi2-2)/3;
        *z = 1;
        break;
    case(20):
        *x = (-dMPhi1-2)/3;
        *y = (dMPhi2-3)/3;
        *z = 1;
        break;
    case(21):
        *x = (-dMPhi1-1)/3;
        *y = (dMPhi2-3)/3;
        *z = 1;
        break;
    case(22):
        *x = (-dMPhi1)/3;
        *y = (dMPhi2-3)/3;
        *z = 1;
        break;
    case(23):
        *x = (-dMPhi1+1)/3;
        *y = (dMPhi2-3)/3;
        *z = 1;
        break;
    case(24):
        *x = (-dMPhi1+2)/3;
        *y = (dMPhi2-3)/3;
        *z = 1;
        break;
    case(25):
        *x = (-dMPhi1+3)/3;
        *y = (dMPhi2-3)/3;
        *z = 1;
        break;
    case(26):
        *x = (-dMPhi1+3)/3;
        *y = (dMPhi2-2)/3;
        *z = 1;
        break;
    case(27):
        *x = (-dMPhi1+3)/3;
        *y = (dMPhi2-1)/3;
        *z = 1;
        break;
    case(28):
        *x = (-dMPhi1+3)/3;
        *y = (dMPhi2)/3;
        *z = 1;
        break;
    case(29):
        *x = (-dMPhi1+3)/3;
        *y = (dMPhi2+1)/3;
        *z = 1;
        break;
    case(30):
        *x = (-dMPhi1+3)/3;
        *y = (dMPhi2+2)/3;
        *z = 1;
        break;
    case(31):
        *x = (-dMPhi1+2)/3;
        *y = (dMPhi2+2)/3;
        *z = 1;
        break;
    case(32):
        *x = (-dMPhi1+1)/3;
        *y = (dMPhi2+2)/3;
        *z = 1;
        break;
    case(33):
        *x = (-dMPhi1)/3;
        *y = (dMPhi2+2)/3;
        *z = 1;
        break;
    case(34):
        *x = (-dMPhi1-1)/3;
        *y = (dMPhi2+2)/3;
        *z = 1;
        break;
    case(35):
        *x = (-dMPhi1-2)/3;
        *y = (dMPhi2+2)/3;
        *z = 1;
        break;
    case(36):
        *x = -1;
        *y = (dMPhi1+2)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(37):
        *x = -1;
        *y = (dMPhi1+1)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(38):
        *x = -1;
        *y = (dMPhi1)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(39):
        *x = -1;
        *y = (dMPhi1-1)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(40):
        *x = -1;
        *y = (dMPhi1-2)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(41):
        *x = -1;
        *y = (dMPhi1-3)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(42):
        *x = (-dMPhi1-2)/3;
        *y = -1;
        *z = (dMPhi2+2)/3;
        break;
    case(43):
        *x = (-dMPhi1-1)/3;
        *y = -1;
        *z = (dMPhi2+2)/3;
        break;
    case(44):
        *x = (-dMPhi1)/3;
        *y = -1;
        *z = (dMPhi2+2)/3;
        break;
    case(45):
        *x = (-dMPhi1+1)/3;
        *y = -1;
        *z = (dMPhi2+2)/3;
        break;
    case(46):
        *x = (-dMPhi1+2)/3;
        *y = -1;
        *z = (dMPhi2+2)/3;
        break;
    case(47):
        *x = (-dMPhi1+3)/3;
        *y = -1;
        *z = (dMPhi2+2)/3;
        break;
    case(48):
        *x = 1;
        *y = (dMPhi1-3)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(49):
        *x = 1;
        *y = (dMPhi1-2)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(50):
        *x = 1;
        *y = (dMPhi1-1)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(51):
        *x = 1;
        *y = (dMPhi1)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(52):
        *x = 1;
        *y = (dMPhi1+1)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(53):
        *x = 1;
        *y = (dMPhi1+2)/3;
        *z = (dMPhi2+2)/3;
        break;
    case(54):
        *x = (-dMPhi1+3)/3;
        *y = 1;
        *z = (dMPhi2+2)/3;
        break;
    case(55):
        *x = (-dMPhi1+2)/3;
        *y = 1;
        *z = (dMPhi2+2)/3;
        break;
    case(56):
        *x = (-dMPhi1+1)/3;
        *y = 1;
        *z = (dMPhi2+2)/3;
        break;
    case(57):
        *x = (-dMPhi1)/3;
        *y = 1;
        *z = (dMPhi2+2)/3;
        break;
    case(58):
        *x = (-dMPhi1-1)/3;
        *y = 1;
        *z = (dMPhi2+2)/3;
        break;
    case(59):
        *x = (-dMPhi1-2)/3;
        *y = 1;
        *z = (dMPhi2+2)/3;
        break;
    case(60):
        *x = -1;
        *y = (dMPhi1+2)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(61):
        *x = -1;
        *y = (dMPhi1+1)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(62):
        *x = -1;
        *y = (dMPhi1)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(63):
        *x = -1;
        *y = (dMPhi1-1)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(64):
        *x = -1;
        *y = (dMPhi1-2)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(65):
        *x = -1;
        *y = (dMPhi1-3)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(66):
        *x = (-dMPhi1-2)/3;
        *y = -1;
        *z = (dMPhi2+1)/3;
        break;
    case(67):
        *x = (-dMPhi1-1)/3;
        *y = -1;
        *z = (dMPhi2+1)/3;
        break;
    case(68):
        *x = (-dMPhi1)/3;
        *y = -1;
        *z = (dMPhi2+1)/3;
        break;
    case(69):
        *x = (-dMPhi1+1)/3;
        *y = -1;
        *z = (dMPhi2+1)/3;
        break;
    case(70):
        *x = (-dMPhi1+2)/3;
        *y = -1;
        *z = (dMPhi2+1)/3;
        break;
    case(71):
        *x = (-dMPhi1+3)/3;
        *y = -1;
        *z = (dMPhi2+1)/3;
        break;
    case(72):
        *x = 1;
        *y = (dMPhi1-3)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(73):
        *x = 1;
        *y = (dMPhi1-2)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(74):
        *x = 1;
        *y = (dMPhi1-1)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(75):
        *x = 1;
        *y = (dMPhi1)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(76):
        *x = 1;
        *y = (dMPhi1+1)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(77):
        *x = 1;
        *y = (dMPhi1+2)/3;
        *z = (dMPhi2+1)/3;
        break;
    case(78):
        *x = (-dMPhi1+3)/3;
        *y = 1;
        *z = (dMPhi2+1)/3;
        break;
    case(79):
        *x = (-dMPhi1+2)/3;
        *y = 1;
        *z = (dMPhi2+1)/3;
        break;
    case(80):
        *x = (-dMPhi1+1)/3;
        *y = 1;
        *z = (dMPhi2+1)/3;
        break;
    case(81):
        *x = (-dMPhi1)/3;
        *y = 1;
        *z = (dMPhi2+1)/3;
        break;
    case(82):
        *x = (-dMPhi1-1)/3;
        *y = 1;
        *z = (dMPhi2+1)/3;
        break;
    case(83):
        *x = (-dMPhi1-2)/3;
        *y = 1;
        *z = (dMPhi2+1)/3;
        break;
    case(84):
        *x = -1;
        *y = (dMPhi1+2)/3;
        *z = (dMPhi2)/3;
        break;
    case(85):
        *x = -1;
        *y = (dMPhi1+1)/3;
        *z = (dMPhi2)/3;
        break;
    case(86):
        *x = -1;
        *y = (dMPhi1)/3;
        *z = (dMPhi2)/3;
        break;
    case(87):
        *x = -1;
        *y = (dMPhi1-1)/3;
        *z = (dMPhi2)/3;
        break;
    case(88):
        *x = -1;
        *y = (dMPhi1-2)/3;
        *z = (dMPhi2)/3;
        break;
    case(89):
        *x = -1;
        *y = (dMPhi1-3)/3;
        *z = (dMPhi2)/3;
        break;
    case(90):
        *x = (-dMPhi1-2)/3;
        *y = -1;
        *z = (dMPhi2)/3;
        break;
    case(91):
        *x = (-dMPhi1-1)/3;
        *y = -1;
        *z = (dMPhi2)/3;
        break;
    case(92):
        *x = (-dMPhi1)/3;
        *y = -1;
        *z = (dMPhi2)/3;
        break;
    case(93):
        *x = (-dMPhi1+1)/3;
        *y = -1;
        *z = (dMPhi2)/3;
        break;
    case(94):
        *x = (-dMPhi1+2)/3;
        *y = -1;
        *z = (dMPhi2)/3;
        break;
    case(95):
        *x = (-dMPhi1+3)/3;
        *y = -1;
        *z = (dMPhi2)/3;
        break;
    case(96):
        *x = 1;
        *y = (dMPhi1-3)/3;
        *z = (dMPhi2)/3;
        break;
    case(97):
        *x = 1;
        *y = (dMPhi1-2)/3;
        *z = (dMPhi2)/3;
        break;
    case(98):
        *x = 1;
        *y = (dMPhi1-1)/3;
        *z = (dMPhi2)/3;
        break;
    case(99):
        *x = 1;
        *y = (dMPhi1)/3;
        *z = (dMPhi2)/3;
        break;
    case(100):
        *x = 1;
        *y = (dMPhi1+1)/3;
        *z = (dMPhi2)/3;
        break;
    case(101):
        *x = 1;
        *y = (dMPhi1+2)/3;
        *z = (dMPhi2)/3;
        break;
    case(102):
        *x = (-dMPhi1+3)/3;
        *y = 1;
        *z = (dMPhi2)/3;
        break;
    case(103):
        *x = (-dMPhi1+2)/3;
        *y = 1;
        *z = (dMPhi2)/3;
        break;
    case(104):
        *x = (-dMPhi1+1)/3;
        *y = 1;
        *z = (dMPhi2)/3;
        break;
    case(105):
        *x = (-dMPhi1)/3;
        *y = 1;
        *z = (dMPhi2)/3;
        break;
    case(106):
        *x = (-dMPhi1-1)/3;
        *y = 1;
        *z = (dMPhi2)/3;
        break;
    case(107):
        *x = (-dMPhi1-2)/3;
        *y = 1;
        *z = (dMPhi2)/3;
        break;
    default:
        *x = 0.0;
        *y = 0.0;
        *z = 0.0;
        break;
    }
}

void fSWIGTraj192(long u_lTrig, double dMPhi1, double dMPhi2, double* x, double* y, double *z)
{
    switch(u_lTrig%192) {
    case(0):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(1):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(2):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(3):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(4):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(5):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(6):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(7):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(8):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(9):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(10):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(11):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(12):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(13):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(14):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(15):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(16):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(17):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(18):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(19):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(20):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(21):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(22):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(23):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(24):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(25):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(26):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(27):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(28):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(29):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(30):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(31):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(32):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(33):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(34):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(35):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(36):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(37):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(38):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(39):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(40):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(41):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(42):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(43):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(44):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(45):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(46):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(47):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(48):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(49):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2-4)/4;
        *z = 1;
        break;
    case(50):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2-3)/4;
        *z = 1;
        break;
    case(51):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2-2)/4;
        *z = 1;
        break;
    case(52):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2-1)/4;
        *z = 1;
        break;
    case(53):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2)/4;
        *z = 1;
        break;
    case(54):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2+1)/4;
        *z = 1;
        break;
    case(55):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2+2)/4;
        *z = 1;
        break;
    case(56):
        *x = (-dMPhi1+4)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(57):
        *x = (-dMPhi1+3)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(58):
        *x = (-dMPhi1+2)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(59):
        *x = (-dMPhi1+1)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(60):
        *x = (-dMPhi1)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(61):
        *x = (-dMPhi1-1)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(62):
        *x = (-dMPhi1-2)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(63):
        *x = (-dMPhi1-3)/4;
        *y = (dMPhi2+3)/4;
        *z = 1;
        break;
    case(64):
        *x = -1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(65):
        *x = -1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(66):
        *x = -1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(67):
        *x = -1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(68):
        *x = -1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(69):
        *x = -1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(70):
        *x = -1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(71):
        *x = -1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(72):
        *x = (-dMPhi1-3)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(73):
        *x = (-dMPhi1-2)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(74):
        *x = (-dMPhi1-1)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(75):
        *x = (-dMPhi1)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(76):
        *x = (-dMPhi1+1)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(77):
        *x = (-dMPhi1+2)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(78):
        *x = (-dMPhi1+3)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(79):
        *x = (-dMPhi1+4)/4;
        *y = -1;
        *z = (dMPhi2+3)/4;
        break;
    case(80):
        *x = 1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(81):
        *x = 1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(82):
        *x = 1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(83):
        *x = 1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(84):
        *x = 1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(85):
        *x = 1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(86):
        *x = 1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(87):
        *x = 1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2+3)/4;
        break;
    case(88):
        *x = (-dMPhi1+4)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(89):
        *x = (-dMPhi1+3)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(90):
        *x = (-dMPhi1+2)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(91):
        *x = (-dMPhi1+1)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(92):
        *x = (-dMPhi1)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(93):
        *x = (-dMPhi1-1)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(94):
        *x = (-dMPhi1-2)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(95):
        *x = (-dMPhi1-3)/4;
        *y = 1;
        *z = (dMPhi2+3)/4;
        break;
    case(96):
        *x = -1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(97):
        *x = -1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(98):
        *x = -1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(99):
        *x = -1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(100):
        *x = -1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(101):
        *x = -1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(102):
        *x = -1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(103):
        *x = -1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(104):
        *x = (-dMPhi1-3)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(105):
        *x = (-dMPhi1-2)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(106):
        *x = (-dMPhi1-1)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(107):
        *x = (-dMPhi1)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(108):
        *x = (-dMPhi1+1)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(109):
        *x = (-dMPhi1+2)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(110):
        *x = (-dMPhi1+3)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(111):
        *x = (-dMPhi1+4)/4;
        *y = -1;
        *z = (dMPhi2+2)/4;
        break;
    case(112):
        *x = 1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(113):
        *x = 1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(114):
        *x = 1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(115):
        *x = 1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(116):
        *x = 1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(117):
        *x = 1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(118):
        *x = 1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(119):
        *x = 1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2+2)/4;
        break;
    case(120):
        *x = (-dMPhi1+4)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(121):
        *x = (-dMPhi1+3)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(122):
        *x = (-dMPhi1+2)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(123):
        *x = (-dMPhi1+1)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(124):
        *x = (-dMPhi1)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(125):
        *x = (-dMPhi1-1)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(126):
        *x = (-dMPhi1-2)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(127):
        *x = (-dMPhi1-3)/4;
        *y = 1;
        *z = (dMPhi2+2)/4;
        break;
    case(128):
        *x = -1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(129):
        *x = -1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(130):
        *x = -1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(131):
        *x = -1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(132):
        *x = -1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(133):
        *x = -1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(134):
        *x = -1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(135):
        *x = -1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(136):
        *x = (-dMPhi1-3)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(137):
        *x = (-dMPhi1-2)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(138):
        *x = (-dMPhi1-1)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(139):
        *x = (-dMPhi1)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(140):
        *x = (-dMPhi1+1)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(141):
        *x = (-dMPhi1+2)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(142):
        *x = (-dMPhi1+3)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(143):
        *x = (-dMPhi1+4)/4;
        *y = -1;
        *z = (dMPhi2+1)/4;
        break;
    case(144):
        *x = 1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(145):
        *x = 1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(146):
        *x = 1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(147):
        *x = 1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(148):
        *x = 1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(149):
        *x = 1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(150):
        *x = 1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(151):
        *x = 1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2+1)/4;
        break;
    case(152):
        *x = (-dMPhi1+4)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(153):
        *x = (-dMPhi1+3)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(154):
        *x = (-dMPhi1+2)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(155):
        *x = (-dMPhi1+1)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(156):
        *x = (-dMPhi1)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(157):
        *x = (-dMPhi1-1)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(158):
        *x = (-dMPhi1-2)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(159):
        *x = (-dMPhi1-3)/4;
        *y = 1;
        *z = (dMPhi2+1)/4;
        break;
    case(160):
        *x = -1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2)/4;
        break;
    case(161):
        *x = -1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2)/4;
        break;
    case(162):
        *x = -1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2)/4;
        break;
    case(163):
        *x = -1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2)/4;
        break;
    case(164):
        *x = -1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2)/4;
        break;
    case(165):
        *x = -1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2)/4;
        break;
    case(166):
        *x = -1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2)/4;
        break;
    case(167):
        *x = -1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2)/4;
        break;
    case(168):
        *x = (-dMPhi1-3)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(169):
        *x = (-dMPhi1-2)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(170):
        *x = (-dMPhi1-1)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(171):
        *x = (-dMPhi1)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(172):
        *x = (-dMPhi1+1)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(173):
        *x = (-dMPhi1+2)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(174):
        *x = (-dMPhi1+3)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(175):
        *x = (-dMPhi1+4)/4;
        *y = -1;
        *z = (dMPhi2)/4;
        break;
    case(176):
        *x = 1;
        *y = (dMPhi1-4)/4;
        *z = (dMPhi2)/4;
        break;
    case(177):
        *x = 1;
        *y = (dMPhi1-3)/4;
        *z = (dMPhi2)/4;
        break;
    case(178):
        *x = 1;
        *y = (dMPhi1-2)/4;
        *z = (dMPhi2)/4;
        break;
    case(179):
        *x = 1;
        *y = (dMPhi1-1)/4;
        *z = (dMPhi2)/4;
        break;
    case(180):
        *x = 1;
        *y = (dMPhi1)/4;
        *z = (dMPhi2)/4;
        break;
    case(181):
        *x = 1;
        *y = (dMPhi1+1)/4;
        *z = (dMPhi2)/4;
        break;
    case(182):
        *x = 1;
        *y = (dMPhi1+2)/4;
        *z = (dMPhi2)/4;
        break;
    case(183):
        *x = 1;
        *y = (dMPhi1+3)/4;
        *z = (dMPhi2)/4;
        break;
    case(184):
        *x = (-dMPhi1+4)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(185):
        *x = (-dMPhi1+3)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(186):
        *x = (-dMPhi1+2)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(187):
        *x = (-dMPhi1+1)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(188):
        *x = (-dMPhi1)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(189):
        *x = (-dMPhi1-1)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(190):
        *x = (-dMPhi1-2)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    case(191):
        *x = (-dMPhi1-3)/4;
        *y = 1;
        *z = (dMPhi2)/4;
        break;
    default:
        *x = 0.0;
        *y = 0.0;
        *z = 0.0;
        break;
    }
}
